development:
  adapter: postgresql
  encoding: utf8
  database: project_management_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_management_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_management_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST